services:
  postgres:
    image: postgres:17-alpine
    container_name: events_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: events_mq
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  rabbitmq_data: