services:
  postgres:
    image: postgres:18-alpine
    container_name: events_db
    networks:
      - backend
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: events_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: events_mq
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  backend:

volumes:
  postgres_data:
  rabbitmq_data: